// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "DAISIE_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// TRAISIE_branch_rcpp
Rcpp::List TRAISIE_branch_rcpp(const Rcpp::NumericVector& lambda_cs, const Rcpp::NumericVector& lambda_as, const Rcpp::NumericVector& mus, const Rcpp::NumericVector& gammas, const Rcpp::NumericMatrix& qs, const double& p, const Rcpp::NumericVector& tma, const std::string& chosen_interval, const std::string& inte_method, const Rcpp::NumericVector& init_states, const Rcpp::NumericVector& time, double atol, double rtol);
RcppExport SEXP _DAISIE_TRAISIE_branch_rcpp(SEXP lambda_csSEXP, SEXP lambda_asSEXP, SEXP musSEXP, SEXP gammasSEXP, SEXP qsSEXP, SEXP pSEXP, SEXP tmaSEXP, SEXP chosen_intervalSEXP, SEXP inte_methodSEXP, SEXP init_statesSEXP, SEXP timeSEXP, SEXP atolSEXP, SEXP rtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda_cs(lambda_csSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda_as(lambda_asSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mus(musSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gammas(gammasSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type qs(qsSEXP);
    Rcpp::traits::input_parameter< const double& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tma(tmaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type chosen_interval(chosen_intervalSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type inte_method(inte_methodSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type init_states(init_statesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type atol(atolSEXP);
    Rcpp::traits::input_parameter< double >::type rtol(rtolSEXP);
    rcpp_result_gen = Rcpp::wrap(TRAISIE_branch_rcpp(lambda_cs, lambda_as, mus, gammas, qs, p, tma, chosen_interval, inte_method, init_states, time, atol, rtol));
    return rcpp_result_gen;
END_RCPP
}
