DAISIE_bootstrap <- function(sim_time,
                             sim_M,
                             sim_pars,
                             sim_replicates,
                             sim_divdepmodel,
                             ddmodel_sim = 11,
                             island_type = "oceanic",
                             nonoceanic_pars = NULL,
                             k_dist_pars = NULL,
                             num_guilds = NULL,
                             prop_type2_pool = NA,
                             replicates_apply_type2 = TRUE,
                             sample_freq = 25,
                             plot_sims = TRUE,
                             island_ontogeny = "const",
                             area_pars = NULL,
                             ext_pars = NULL,
                             sea_level = "const",
                             pars_shift = FALSE,
                             verbose = TRUE) {

}
