# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Driver for the boost::odeint solver
#'
#' @export
DAISIE_odeint_cs <- function(runmod, y, times, lx, kk, par, Stepper, atol, rtol) {
    .Call(`_DAISIE_DAISIE_odeint_cs`, runmod, y, times, lx, kk, par, Stepper, atol, rtol)
}

#' CS iteration control
#'
#' Sets or retrieves the max. number of iterations used by the odeint solver.
#'
#' @param max_steps \code{max_steps}: sets max. iterations to \code{max_steps}. \cr
#' @return current max. iterations
#'
#' @export
DAISIE_CS_max_steps <- function(rmax_steps) {
    .Call(`_DAISIE_DAISIE_CS_max_steps`, rmax_steps)
}

#'
#' Sets or retrieves the factor to calculate the step-size used by the odeint::adams_bashforth[_moulton] solvers.
#'
#' @param factor sets step-size to \code{factor * (t1 - t0)}. \cr
#' @return current factor
#'
#' @export
DAISIE_abm_factor <- function(rfactor) {
    .Call(`_DAISIE_DAISIE_abm_factor`, rfactor)
}

#' Driver for the boost::odeint solver
#'
#' @export
DAISIE_odeint_iw <- function(y, times, pars, Stepper, atol, reltol) {
    .Call(`_DAISIE_DAISIE_odeint_iw`, y, times, pars, Stepper, atol, reltol)
}

#' IW concurrency control
#'
#' Sets or retrieves the number of threads used by the odeint solver.
#'
#' @param num_threads \code{num_threads < 0, omitted}: retrieves number of threads. \cr
#' \code{num_threads = 0}: sets the number of threads to the number of available cores. \cr
#' \code{num_threads = 1}: single-threaded execution. \cr
#' \code{num_threads > 1}: sets the number of threads to \code{num_threads}.
#' @return number of threads
#' @note The maximum number of threads is limited to the value of the C++
#' standard library function \code{std::thread::hardware_concurrency()}.
#' This is also the default number of threads upon library load.
#' Multithreading incurs some overhead. Therefore, single-threaded execution
#' might be faster for small systems.
#' @examples
#' DAISIE_IW_num_threads(as.integer(Sys.getenv("OMP_NUM_THREADS"))
#' @export
DAISIE_IW_num_threads <- function(rnum_threads = NULL) {
    .Call(`_DAISIE_DAISIE_IW_num_threads`, rnum_threads)
}

