# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp RcppEigen BH
#' @export daisie_odeint_iw
NULL

#' Driver for boos::odeint
#' @name daisie_odeint_iw
NULL

